export const works = {
  characterList: [
    {
      id: 1,
      name: "Luke Skywalker",
      gender: "male",
      species: [],
      birthYear: "19BBY",
      eyeColor: "blue",
      films: [1, 2, 3, 6],
      url: "https://swapi.dev/api/people/1/",
    },
    {
      id: 2,
      name: "C-3PO",
      gender: "n/a",
      species: ["https://swapi.dev/api/species/2/"],
      birthYear: "112BBY",
      eyeColor: "yellow",
      films: [1, 2, 3, 4, 5, 6],
      url: "https://swapi.dev/api/people/2/",
    },
    {
      id: 3,
      name: "R2-D2",
      gender: "n/a",
      species: ["https://swapi.dev/api/species/2/"],
      birthYear: "33BBY",
      eyeColor: "red",
      films: [1, 2, 3, 4, 5, 6],
      url: "https://swapi.dev/api/people/3/",
    },
    {
      id: 4,
      name: "Darth Vader",
      gender: "male",
      species: [],
      birthYear: "41.9BBY",
      eyeColor: "yellow",
      films: [1, 2, 3, 6],
      url: "https://swapi.dev/api/people/4/",
    },
    {
      id: 5,
      name: "Leia Organa",
      gender: "female",
      species: [],
      birthYear: "19BBY",
      eyeColor: "brown",
      films: [1, 2, 3, 6],
      url: "https://swapi.dev/api/people/5/",
    },
    {
      id: 6,
      name: "Owen Lars",
      gender: "male",
      species: [],
      birthYear: "52BBY",
      eyeColor: "blue",
      films: [1, 5, 6],
      url: "https://swapi.dev/api/people/6/",
    },
    {
      id: 7,
      name: "Beru Whitesun lars",
      gender: "female",
      species: [],
      birthYear: "47BBY",
      eyeColor: "blue",
      films: [1, 5, 6],
      url: "https://swapi.dev/api/people/7/",
    },
    {
      id: 8,
      name: "R5-D4",
      gender: "n/a",
      species: ["https://swapi.dev/api/species/2/"],
      birthYear: "unknown",
      eyeColor: "red",
      films: [1],
      url: "https://swapi.dev/api/people/8/",
    },
    {
      id: 9,
      name: "Biggs Darklighter",
      gender: "male",
      species: [],
      birthYear: "24BBY",
      eyeColor: "brown",
      films: [1],
      url: "https://swapi.dev/api/people/9/",
    },
    {
      id: 10,
      name: "Obi-Wan Kenobi",
      gender: "male",
      species: [],
      birthYear: "57BBY",
      eyeColor: "blue-gray",
      films: [1, 2, 3, 4, 5, 6],
      url: "https://swapi.dev/api/people/10/",
    },
  ],
  pages: 8,
  isLoading: false,
  isError: undefined,
};

export const fails = {
  characterList: null,
  isLoading: false,
  isError: true,
};
